USE FinalTerm
GO

USE LAB4
GO

INSERT INTO CUSTOMERS(CUSTOMER_NAME, USERNAME, PASSWORD, ADDRESS, EMAIL, PHONE)
VALUES ('Azazel', 'AzazelDevel', '123', '86A3', 'admin@test.com', '0123456789')

INSERT INTO BRANCH (BRANCH_NAME, BRANCH_ADDRESS)
VALUES ('Test', 'Test')

DROP DATABASE FinalTerm

DROP TABLE SEATS
DROP TABLE BRANCH

ALTER TABLE CUSTOMER_DETAILS DROP CONSTRAINT FK_CustomerDetails_CustomerID;
ALTER TABLE SEATS DROP CONSTRAINT FK_Seats_BranchID;
ALTER TABLE ORDERS DROP CONSTRAINT FK_Orders_CustomerID;
ALTER TABLE ORDERS DROP CONSTRAINT FK_Orders_ProductID;
ALTER TABLE ORDERS DROP CONSTRAINT FK_Orders_SeatID;
ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_OrderDetails_OrderID;


SELECT * FROM CUSTOMER_DETAILS
SELECT * FROM SEATS
SELECT * FROM ORDER_DETAILS
SELECT * FROM ORDERS
SELECT * FROM CUSTOMERS
SELECT * FROM PRODUCTS
SELECT * FROM BRANCH

DROP TABLE CUSTOMER_DETAILS;
DROP TABLE SEATS;
DROP TABLE ORDER_DETAILS;
DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE PRODUCTS;
DROP TABLE BRANCH;

